---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    name: hello-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: hello